[worldserver]

AutoBalance.Enable.Global = 1
AutoBalance.Enable.5M = 1

AutoBalance.LevelScaling = 1
AutoBalance.LevelScaling.Method = "dynamic"
AutoBalance.LevelScaling.SkipLowerLevels = 0
AutoBalance.LevelScaling.DynamicLevel.Ceiling.Dungeons = 1
AutoBalance.LevelScaling.DynamicLevel.Floor.Dungeons = 5

AutoBalance.Timewalking.Enable = 1
AutoBalance.Timewalking.BossToken = 9000051
AutoBalance.Timewalking.StatMultiplier = 1.5
AutoBalance.Timewalking.MapIDs = "36, 33, 43, 48, 34, 90, 47, 189, 129, 70, 209, 349, 109, 230, 229, 289, 329, 389, 429, 430, 431, 543, 542, 547, 546, 557, 558, 560, 269, 555, 556, 545, 553, 554, 540, 552"

AutoBalance.reward.enable = 0
AutoBalance.PlayerChangeNotify = 0
AutoBalanceAnnounce.enable = 0
